apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tmusic

commonLabels:
  app.kubernetes.io/part-of: tmusic

resources:
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - bot-migrate-job.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

images:
  - name: ghcr.io/example/tmusic-backend
    newTag: latest
